### ISSUE TITLE
JCenter 要停止服务了，建议切换仓库

### ISSUE THREAD

**Issue by yorhaha** [treehollow/treehollow-v3-android#1]
如题，详细可查看公众号“郭霖”4月20日的推送

**Comment by UNIDY2002** [comment]
4月27日JFrog表示

> We listened to the community and will keep JCenter as a read-only repository indefinitely. Our customers and the community can continue to rely on JCenter as a reliable mirror for Java packages.

所以现在看起来安全了

来源：https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/
